/**
 * Store global settings (CONFIG)
 */
export default {
  APP_VERSION: APP_VERSION,
  APP_PACKAGE_VERSION: APP_PACKAGE_VERSION,
  __ELECTRON__: __ELECTRON__,
  CORE_ASSET: CORE_ASSET,
  FAUCET_URL: FAUCET_URL,
  FAUCET_FILE: FAUCET_FILE,
  BLOCKCHAIN_URL: BLOCKCHAIN_URL,
  BITSHARES_WS: BITSHARES_WS,
  SOFTWARE_UPDATE_REFERENCE_ACCOUNT_NAME: SOFTWARE_UPDATE_REFERENCE_ACCOUNT_NAME
};