export default {
    GAMES: 'GAMES',
    GAMES_ROCK_PAPER_SCISSOR_TOURNAMENTS: 'GAMES_ROCK_PAPER_SCISSOR_TOURNAMENTS',
    EXCHANGE: 'EXCHANGE',
    EXPLORER_BLOCK_CHAIN: 'EXPLORER_BLOCK_CHAIN',
    EXPLORER_FEE_SCHEDULE: 'EXPLORER_FEE_SCHEDULE',
    EXPLORER_ACCOUNTS: 'EXPLORER_ACCOUNTS',
    DASHBOARD_BALANCES: 'DASHBOARD_BALANCES',
    SEND: 'SEND',
    VOTING: 'VOTING',
    DEPOSIT_WITHDRAW: 'DEPOSIT_WITHDRAW'
}
