export default {
  /**
 * Game Tabs
 */
  GAME_RPS_CHANGE_TAB_PARAMS: 'GAME_RPS_CHANGE_TAB_PARAMS',
  /**
 * Dashboard Tab
 */
  GAME_RPS_SET_DASHBOARD_LIST: 'GAME_RPS_SET_DASHBOARD_LIST',
  /**
 * Find Tab
 */
  GAME_RPS_SET_FIND_LIST: 'GAME_RPS_SET_FIND_LIST',
  GAME_RPS_SET_FIND_DD_CURRENT: 'GAME_RPS_SET_FIND_DD_CURRENT',
  /**
 * Explore Tab
 */
  GAME_RPS_SET_EXPLORE_LIST: 'GAME_RPS_SET_EXPLORE_LIST',
  GAME_RPS_SET_EXPLORE_DD_CURRENT: 'GAME_RPS_SET_EXPLORE_DD_CURRENT',
  GAME_RPS_SET_EXPLORE_SORT: 'GAME_RPS_SET_EXPLORE_SORT',
  GAME_RPS_SET_EXPLORE_PAGE: 'GAME_RPS_SET_EXPLORE_PAGE',
  GAME_RPS_SET_EXPLORE_COUNT_PAGES: 'GAME_RPS_SET_EXPLORE_COUNT_PAGES',

  /**
     * Create
     */
  GAME_RPS_SET_AVAILABLE_UNITS: 'GAME_RPS_SET_AVAILABLE_UNITS',

  /**
 * Game
 */
  GAME_RPS_SET_GAME: 'GAME_RPS_SET_GAME',
  GAME_RPS_SET_AWAITING_GAME_START: 'GAME_RPS_SET_AWAITING_GAME_START',
  GAME_RPS_SET_CONCLUDED_GAME_START: 'GAME_RPS_SET_CONCLUDED_GAME_START',
  GAME_RPS_SET_ACTIVE_GAME: 'GAME_RPS_SET_ACTIVE_GAME',

};
