// List all the actions type used in the app here
export default {
  // Asset Actions
  ASSET_RECEIVE_LIST: 'ASSET_RECEIVE_LIST',
  // App Actions
  APP_SET_ACCOUNT: 'ASSET_SET_ACCOUNT',
  APP_SET_IS_LOGGED_IN: 'APP_SET_IS_LOGGED_IN',
  // Register Actions
  REGISTER_SET_LOADING_STATUS: 'REGISTER_SET_LOADING_STATUS',
  REGISTER_SET_ERROR: 'REGISTER_SET_ERROR',
  // Login Actions
  LOGIN_SET_LOADING_STATUS: 'LOGIN_SET_LOADING_STATUS',
  LOGIN_SET_ERROR: 'LOGIN_SET_ERROR',
  // Sport Actions
  SPORT_SET_GET_SPORTS_LOADING_STATUS: 'SPORT_SET_GET_SPORTS_LOADING_STATUS',
  SPORT_ADD_SPORTS: 'SPORT_ADD_SPORTS',
  // Event Group Actions
  EVENT_GROUP_SET_GET_EVENT_GROUPS_LOADING_STATUS: 'EVENT_GROUP_SET_GET_EVENT_GROUPS_LOADING_STATUS',
  EVENT_GROUP_ADD_EVENT_GROUPS: 'EVENT_GROUP_ADD_EVENT_GROUPS',
  // Competitor Actions
  COMPETITOR_SET_GET_COMPETITORS_LOADING_STATUS: 'COMPETITOR_SET_GET_COMPETITORS_LOADING_STATUS',
  COMPETITOR_ADD_COMPETITORS: 'COMPETITOR_ADD_COMPETITORS',
  // Event Group Actions
  EVENT_SET_GET_EVENTS_LOADING_STATUS: 'EVENT_SET_GET_EVENTS_LOADING_STATUS',
  EVENT_ADD_EVENTS: 'EVENT_ADD_EVENTS',
  EVENT_SET_SEARCH_EVENTS_LOADING_STATUS: 'EVENT_SET_SEARCH_EVENTS_LOADING_STATUS',
  EVENT_SET_SEARCH_RESULT: 'EVENT_SET_SEARCH_RESULT',
  // Betting Market Group Actions
  BETTING_MARKET_GROUP_ADD_BETTING_MARKET_GROUPS: 'BETTING_MARKET_GROUP_ADD_BETTING_MARKET_GROUPS',
  // Betting Market  Actions
  BETTING_MARKET_ADD_BETTING_MARKETS: 'BETTING_MARKET_ADD_BETTING_MARKETS',
  // Bet Actions
  BET_SET_GET_ONGOING_BETS_LOADING_STATUS: 'BET_SET_GET_ONGOING_BETS_LOADING_STATUS',
  BET_SET_GET_RESOLVED_BETS_LOADING_STATUS: 'BET_SET_GET_RESOLVED_BETS_LOADING_STATUS',
  BET_ADD_ONGOING_BETS: 'BET_ADD_ONGOING_BETS',
  BET_ADD_RESOLVED_BETS: 'BET_ADD_RESOLVED_BETS',
  // Setting Actions
  SETTING_UPDATE_LANG: 'SETTING_UPDATE_LANG',
  SETTING_UPDATE_TIMEZONE: 'SETTING_UPDATE_TIMEZONE',
  SETTING_UPDATE_NOTIFICATION: 'SETTING_UPDATE_NOTIFICATION',
  SETTING_UPDATE_CURRENCY_FORMAT: 'SETTING_UPDATE_CURRENCY_FORMAT',

  // Sidebar Actions
  SIDEBAR_UPDATE_COMPLETE_TREE: 'SIDEBAR_UPDATE_COMPLETE_TREE'
}
