const BettingDrawerStates = {
  NO_OVERLAY: 'NO_OVERLAY',
  SUBMIT_BETS_CONFIRMATION: 'SUBMIT_BETS_CONFIRMATION',
  SUBMIT_BETS_WAITING: 'SUBMIT_BETS_WAITING',
  SUBMIT_BETS_ERROR: 'SUBMIT_BETS_ERROR',
  SUBMIT_BETS_SUCCESS: 'SUBMIT_BETS_SUCCESS',
  DELETE_BETS_CONFIRMATION: 'DELETE_BETS_CONFIRMATION',
  DELETE_BET_CONFIRMATION: 'DELETE_BET_CONFIRMATION',
  DISCONNECTED_ERROR: 'DISCONNECTED_ERROR',
  INSUFFICIENT_BALANCE_ERROR: 'INSUFFICIENT_BALANCE_ERROR'
};

export default BettingDrawerStates;
