const BettingDrawerStates = {
  NO_OVERLAY: 'NO_OVERLAY',
  BET_SLIP_CONFIRMATION: 'BET_SLIP_CONFIRMATION',
  BET_SLIP_WAITING: 'BET_SLIP_WAITING',
  BET_SLIP_ERROR: 'BET_SLIP_ERROR',
  BET_SLIP_SUCCESS: 'BET_SLIP_SUCCESS',
  DELETE_BETS_CONFIRMATION: 'DELETE_BETS_CONFIRMATION',
  DISCONNECTED_ERROR: 'DISCONNECTED_ERROR',
  INSUFFICIENT_BALANCE_ERROR: 'INSUFFICIENT_BALANCE_ERROR',
}

export default BettingDrawerStates;
