const NotificationTypes = {
  DEPOSIT: 'DEPOSIT',
  BET_RESOLVED: 'BET_RESOLVED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  SOFTWARE_UPDATE_AVAILABLE: 'SOFTWARE_UPDATE_AVAILABLE',
  TRANSACTION_HISTORY_DATA_EXPORTED: 'TRANSACTION_HISTORY_DATA_EXPORTED'
};

export default NotificationTypes;
